# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eee155a01be4f2e6fa722ae8c536a3f6bfdfc4d0f4c8c72a78be0d44dfac7adade04df1e175fd32193ebad57ade388694b1609b8e984ef040ecfdf9befed4de0

test:
  secret_key_base: 2ff384f7970a63ddba07d2464e87abf363a783f6b1e761ee60578eee3a15be85b20fdbc1118740a2c5e5b0eec71209ffdde0253324b0dad539175186e2678ded

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
